Repository SQ-UI/ng-sq-ui, pull requests merged in 2019-05, with the labels that each got.

#181 Develop
  .travis.yml
  README.md
  angular.json
  docs/about-us.md
  package-lock.json
  package.json
  projects/ng-datatable/karma.conf.js
  projects/ng-datetime-picker/karma.conf.js
  projects/ng-modal/karma.conf.js
  projects/ng-sq-common/karma.conf.js
  projects/ng-sq-ui/karma.conf.js
  src/app/app-nav/app-nav.component.spec.ts
  src/app/datatable/datatable-docs/datatable-docs.component.spec.ts
  src/app/datetime-picker/datatime-picker-docs/datatime-picker-docs.component.spec.ts
  src/app/home/home/home.component.html
  src/app/modal/modal-docs/modal-docs.component.spec.ts
  src/app/shared/module-overview/module-overview.component.spec.ts
  src/app/sq-common/common/sq-common.component.spec.ts
  src/app/sq-ui/sq-ui/sq-ui.component.spec.ts
  src/karma.conf.js
  yarn.lock
Labels: dependencies, dependency update

#193 updated number of expected chunks
  .travis.yml
Labels: bug

#194 Develop
  .travis.yml
  package-lock.json
  package.json
  yarn.lock
Labels: bug, dependency update

#204 Add assume yes to npm install command for angular cli
  .travis.yml
Labels: bug

#196 Develop
  .travis.yml
  package-lock.json
  package.json
  projects/ng-datatable/src/test.ts
  projects/ng-datetime-picker/src/test.ts
  projects/ng-modal/src/test.ts
  projects/ng-sq-common/src/test.ts
  projects/ng-sq-ui/src/test.ts
  tsconfig.json
  yarn.lock
Labels: dependencies
