Repository SQ-UI/ng-sq-ui, pull requests merged in 2019-02, with the labels that each got.

#96 Updating live examples and documentation
  README.md
  docs/_sidebar.md
  docs/about-us.md
  docs/datatable-module.md
  docs/datetime-picker-module.md
  docs/directives.md
  docs/enums.md
  docs/form-elements-module.md
  docs/index.html
  docs/interfaces.md
  docs/modal-module.md
  docs/progressbar-module.md
  docs/services.md
  docs/standalone-packages.md
  docs/troubleshooting.md
  package-lock.json
  package.json
  yarn.lock
Labels: documentation

#103 Function ngOnInit has 54 lines of code (exceeds 35 allowed)
  src/app/sq-ui/sq-ui/sq-ui.component.ts
Labels: bug

#110 updating readme files
  README.md
  docs/_coverpage.md
  docs/about-us.md
  projects/ng-datatable/src/README.md
  projects/ng-datetime-picker/src/README.md
  projects/ng-modal/src/README.md
  projects/ng-sq-common/src/README.md
  projects/ng-sq-ui/src/README.md
Labels: documentation

#111 Feature/release 1.1.0
  README.md
  angular.json
  docs/troubleshooting.md
  package.json
  projects/ng-datatable/package.json
  projects/ng-datetime-picker/package.json
  projects/ng-modal/package.json
  projects/ng-sq-common/package.json
  projects/ng-sq-common/src/lib/sq-ui-theme.scss
  projects/ng-sq-common/src/lib/styles/base.scss
  projects/ng-sq-common/src/lib/styles/colors.scss
  projects/ng-sq-common/src/lib/styles/reset.scss
  projects/ng-sq-common/src/lib/styles/utilities.scss
  projects/ng-sq-ui/package.json
  projects/ng-sq-ui/src/lib/styles/form-elements.scss
  src/styles.scss
Labels: enhancement

#109 Develop
  README.md
  angular.json
  docs/_coverpage.md
  docs/about-us.md
  docs/troubleshooting.md
  package-lock.json
  package.json
  projects/ng-datatable/package.json
  projects/ng-datatable/src/README.md
  projects/ng-datetime-picker/package.json
  projects/ng-datetime-picker/src/README.md
  projects/ng-modal/package.json
  projects/ng-modal/src/README.md
  projects/ng-sq-common/package.json
  projects/ng-sq-common/src/README.md
  projects/ng-sq-common/src/lib/sq-ui-theme.scss
  projects/ng-sq-common/src/lib/styles/base.scss
  projects/ng-sq-common/src/lib/styles/colors.scss
  projects/ng-sq-common/src/lib/styles/reset.scss
  projects/ng-sq-common/src/lib/styles/utilities.scss
  projects/ng-sq-ui/package.json
  projects/ng-sq-ui/src/README.md
  projects/ng-sq-ui/src/lib/styles/form-elements.scss
  src/styles.scss
  yarn.lock
Labels: dependencies

#113 Develop
  package-lock.json
  yarn.lock
Labels: dependency update, security

#114 Fix/bump security patches
  package-lock.json
  package.json
  projects/ng-datatable/package.json
  projects/ng-datetime-picker/package.json
  projects/ng-modal/package.json
  projects/ng-modal/src/lib/modal/modal.component.scss
  projects/ng-sq-common/package.json
  projects/ng-sq-ui/package.json
  projects/ng-sq-ui/src/lib/ng-sq-ui.module.ts
Labels: security
