Repository SQ-UI/ng-sq-ui, pull requests merged in 2021-05, with the labels that each got.

#861 Feature/form elements custom templates
  docs/README.md
  docs/_coverpage.md
  docs/_sidebar.md
  docs/about-us.md
  docs/bounty-program.md
  projects/ng-sq-common/src/lib/entities/input-core-component.ts
  projects/ng-sq-ui/package.json
  projects/ng-sq-ui/src/lib/form-elements/checkbox/checkbox-templates.directive.ts
  projects/ng-sq-ui/src/lib/form-elements/checkbox/checkbox.component.html
  projects/ng-sq-ui/src/lib/form-elements/checkbox/checkbox.component.ts
  projects/ng-sq-ui/src/lib/form-elements/dropdown/dropdown-templates.directive.ts
  projects/ng-sq-ui/src/lib/form-elements/dropdown/dropdown.component.html
  projects/ng-sq-ui/src/lib/form-elements/dropdown/dropdown.component.spec.ts
  projects/ng-sq-ui/src/lib/form-elements/dropdown/dropdown.component.ts
  projects/ng-sq-ui/src/lib/form-elements/form-elements.module.ts
  projects/ng-sq-ui/src/lib/form-elements/radiobutton/radiobutton-templates.directive.ts
  projects/ng-sq-ui/src/lib/form-elements/radiobutton/radiobutton.component.html
  projects/ng-sq-ui/src/lib/form-elements/radiobutton/radiobutton.component.ts
  projects/ng-sq-ui/src/lib/form-elements/tags-input/tags-input-templates.directive.ts
  projects/ng-sq-ui/src/lib/form-elements/tags-input/tags-input.component.html
  projects/ng-sq-ui/src/lib/form-elements/tags-input/tags-input.component.spec.ts
  projects/ng-sq-ui/src/lib/form-elements/tags-input/tags-input.component.ts
  projects/ng-sq-ui/src/lib/form-elements/typeahead/typeahead-templates.directive.ts
  projects/ng-sq-ui/src/lib/form-elements/typeahead/typeahead.component.html
  projects/ng-sq-ui/src/lib/form-elements/typeahead/typeahead.component.spec.ts
  projects/ng-sq-ui/src/lib/form-elements/typeahead/typeahead.component.ts
  src/app/shared/collapse-content/collapse-content.component.html
  src/app/shared/collapse-content/collapse-content.component.scss
  src/app/shared/collapse-content/collapse-content.component.ts
  src/app/sq-ui/sq-ui/sq-ui.component.html
  src/app/sq-ui/sq-ui/sq-ui.component.scss
  src/app/sq-ui/sq-ui/sq-ui.component.ts
  src/styles.scss
Labels: New Feature, documentation, in progress

#864 Deps update april 2021
  README.md
  package-lock.json
  package.json
  projects/ng-datatable/README.md
  projects/ng-datetime-picker/README.md
  projects/ng-modal/README.md
  projects/ng-sq-common/README.md
  projects/ng-sq-ui/README.md
Labels: dependencies, documentation

#897 documentation and readme updates
  .github/dependabot.yml
  README.md
  docs/_coverpage.md
  docs/bounty-program.md
  docs/form-elements-module.md
  package.json
  projects/ng-datetime-picker/src/lib/datetime-picker/datetime-picker/datetime-picker.component.spec.ts
  src/app/home/home/home.component.html
Labels: documentation

#922 900 update dependabot
  .github/dependabot.yml
Labels: dependencies, enhancement

#921 Documentation updates
  docs/form-elements-module.md
  package-lock.json
  package.json
Labels: dependency update, documentation

#924 Fix for a minor issue where textarea placeholder does not hide when an initial value is passed
  projects/ng-sq-ui/package.json
  projects/ng-sq-ui/src/lib/form-elements/textarea/textarea.component.html
  projects/ng-sq-ui/src/lib/form-elements/textarea/textarea.component.scss
  projects/ng-sq-ui/src/lib/form-elements/textarea/textarea.component.ts
Labels: bug
