Repository SQ-UI/ng-sq-ui, pull requests merged in 2021-09, with the labels that each got.

#973 Bugfix/reexport interface
  projects/ng-sq-common/package.json
  projects/ng-sq-common/src/index.ts
  projects/ng-sq-common/tsconfig.lib.json
Labels: bug

#975 [!] Readme updates 09 2021
  .all-contributorsrc
  README.md
  docs/bounty-program.md
  projects/ng-datatable/README.md
  projects/ng-datetime-picker/README.md
  projects/ng-modal/README.md
  projects/ng-sq-common/README.md
  projects/ng-sq-ui/README.md
Labels: documentation

#972 Develop
  .all-contributorsrc
  .github/dependabot.yml
  README.md
  docs/bounty-program.md
  docs/form-elements-module.md
  package-lock.json
  package.json
  projects/ng-datatable/README.md
  projects/ng-datatable/package.json
  projects/ng-datetime-picker/README.md
  projects/ng-datetime-picker/package.json
  projects/ng-modal/README.md
  projects/ng-modal/package.json
  projects/ng-sq-common/README.md
  projects/ng-sq-common/package.json
  projects/ng-sq-common/src/index.ts
  projects/ng-sq-common/src/lib/entities/input-core-component.ts
  projects/ng-sq-common/src/lib/ng-sq-common.module.ts
  projects/ng-sq-common/tsconfig.lib.json
  projects/ng-sq-ui/README.md
  projects/ng-sq-ui/package.json
  projects/ng-sq-ui/src/lib/form-elements/checkbox/checkbox.component.ts
  projects/ng-sq-ui/src/lib/form-elements/textarea/textarea.component.html
  projects/ng-sq-ui/src/lib/form-elements/textarea/textarea.component.scss
  projects/ng-sq-ui/src/lib/form-elements/textarea/textarea.component.ts
Labels: enhancement, documentation, dependencies, dependency update

#982 Feature/update angular version to 12
  package-lock.json
  package.json
  projects/ng-sq-ui/src/lib/form-elements/dropdown/dropdown.component.spec.ts
  tsconfig.json
Labels: bug
